INTEREST_TYPES = [
  "Animals",
  "Arts",
  "Beach",
  "Biking",
  "Blogging/Vlogging",
  "Board Games",
  "Boating",
  "Camping",
  "Card Games",
  "Cars",
  "Computers",
  "Cooking",
  "Crafts",
  "Dancing",
  "Dining Out",
  "Exercise",
  "Fishing",
  "Flying",
  "Food/Beverages",
  "Gardening",
  "Hiking",
  "Home Improvement",
  "Hunting",
  "Martial Arts",
  "Meditation",
  "Motorcycles",
  "Movies",
  "Music",
  "Nightlife",
  "Other",
  "Photography",
  "Politics",
  "Reading",
  "Religious Activities",
  "Science/Technology",
  "Sewing",
  "Shopping",
  "Singing",
  "Skiing",
  "Swimming",
  "Team Sports",
  "Tennis",
  "Theater",
  "Traveling",
  "TV",
  "Video Games",
  "Volunteering",
  "Watching Sports",
  "Writing",
  "Yoga"
].freeze
