ORG_TYPES = [
  "Arts & Entertainment",
  "Automotive",
  "Beauty & Spas",
  "Education",
  "Event Planning & Services",
  "Financial Services",
  "Food",
  "Health & Medical",
  "Home Services",
  "Hotels & Travel",
  "Local Services",
  "Mass Media",
  "Nightlife",
  "Other",
  "Pets",
  "Professional Services",
  "Public Services & Government",
  "Real Estate",
  "Religious Organizations",
  "Restaurants",
  "Shopping",
  "Sports & Active Life",
  "Technology"
].freeze
