ORG_TYPES = [
  "Arts & Entertainment",
  "Automotive",
  "Beauty & Spas",
  "Community Center",
  "Education",
  "Event Planning & Services",
  "Financial Services",
  "Food/Beverages",
  "Health & Medical",
  "Home Services",
  "Hotels & Travel",
  "Library",
  "Local Services",
  "Mass Media",
  "Museum",
  "Nightlife",
  "Other",
  "Park",
  "Pets",
  "Professional Services",
  "Public Services & Government",
  "Real Estate",
  "Religious Organization",
  "Restaurants/Cafes",
  "Shopping",
  "Sports & Active Life",
  "Technology",
  "Zoo"
].freeze
