:verbose: false
:concurrency: 5

:timeout: 8

staging:
  :concurrency: 10
production:
  :concurrency: 15

:schedule:
  account_end_date_notifier_worker:
    cron: '0 0 * * *'
    class: AccountEndDateNotifierWorker
  check_ach_deposits_notifier_worker:
    cron: '0 1 * * *'
    class: CheckAchDepositsNotifierWorker
